# -*- coding: utf-8 -*-
"""
Full crawl+parse script for task 13
Mode: Crawl URLs first, then parse each page
Generated by Spider Manager V2.0
"""
import asyncio
import datetime
import sys
import os

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def log(level, msg):
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] [{level}] {msg}", flush=True)


async def main():
    log("INFO", "=" * 50)
    log("INFO", "Starting full crawl + parse job")
    log("INFO", "=" * 50)
    
    # Step 1: Crawl URLs
    log("INFO", "Step 1: Crawling URLs...")
    from crawl_spider import crawl
    urls = await crawl()
    log("INFO", f"Crawled {len(urls)} URLs")
    
    # Step 2: Parse content
    log("INFO", "Step 2: Parsing content...")
    from parse_spider import run as parse_run
    await parse_run()
    
    log("INFO", "=" * 50)
    log("INFO", "Full job completed!")
    log("INFO", "=" * 50)


if __name__ == "__main__":
    asyncio.run(main())
