# -*- coding: utf-8 -*-
"""
Crawl script for task 5
Mode: Crawl-only - Collect URLs and save to database
Generated by Spider Manager V2.0
"""
import json
import time
import asyncio
import datetime
import os
import sys
import pymysql
from lxml import html as lxml_html
from urllib.parse import urljoin

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# === Configuration ===
START_URL = "https://www.ceri.com.cn/xwzx/jcyw/index.html"
ENGINE_NAME = "requests"
MAX_PAGES = 5
TIMEOUT = 30
INTERVAL = 2
HEADERS = {}

LIST_XPATH = '//ul[@class="news-list"]/li//a/@href'

# Database config - from environment or defaults
DB_HOST = os.environ.get("SPIDER_DB_HOST", "192.168.1.191")
DB_PORT = int(os.environ.get("SPIDER_DB_PORT", "3308"))
DB_NAME = os.environ.get("SPIDER_DB_NAME", "spider_260515")
DB_TABLE = os.environ.get("SPIDER_DB_TABLE", "crawler_feachdata")
DB_USER = os.environ.get("SPIDER_DB_USER", "root")
DB_PASSWORD = os.environ.get("SPIDER_DB_PASSWORD", "")

# Task ID for updating stats
TASK_ID = 5


def log(level, msg):
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] [{level}] {msg}", flush=True)


def save_urls_to_db(urls):
    """Save crawled URLs to database."""
    if not urls:
        return 0

    conn = pymysql.connect(
        host=DB_HOST, port=DB_PORT, user=DB_USER, 
        password=DB_PASSWORD, database=DB_NAME,
        charset='utf8mb4', connect_timeout=10
    )
    cursor = conn.cursor()

    count = 0
    for url in urls:
        try:
            cursor.execute(f"SELECT id FROM `{DB_TABLE}` WHERE url = %s", (url,))
            if cursor.fetchone():
                continue

            cursor.execute(
                f"INSERT INTO `{DB_TABLE}` (url, parseflag) VALUES (%s, 0)",
                (url,)
            )
            count += 1
        except Exception as e:
            log("WARNING", f"Failed to insert URL: {e}")

    conn.commit()
    cursor.close()
    conn.close()
    return count


def update_task_stats(crawled_count):
    """Update task crawl stats."""
    try:
        conn = pymysql.connect(
            host=DB_HOST, port=DB_PORT, user=DB_USER,
            password=DB_PASSWORD, database="spider",
            charset='utf8mb4', connect_timeout=10
        )
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE tasks SET total_crawled = total_crawled + %s WHERE id = %s",
            (crawled_count, TASK_ID)
        )
        conn.commit()
        cursor.close()
        conn.close()
    except Exception as e:
        log("WARNING", f"Failed to update task stats: {e}")


async def crawl():
    from app.engine.engine_factory import get_engine
    from app.engine import EngineConfig

    engine = get_engine(ENGINE_NAME)
    all_urls = []

    async with engine:

            # 页码递增模式
            PAGE_URL_TEMPLATE = "https://www.ceri.com.cn/xwzx/jcyw/index_{page_num}.html"
            PAGE_START = 1
            PAGE_STEP = 1

            for page_num_offset in range(MAX_PAGES):
                current_page_num = PAGE_START + page_num_offset * PAGE_STEP
                current_url = PAGE_URL_TEMPLATE.replace("{page_num}", str(current_page_num))
                log("INFO", f"Fetching page {page_num_offset + 1}: {current_url}")

                ec = EngineConfig(url=current_url, headers=HEADERS, timeout=TIMEOUT)
                resp = await engine.fetch(ec)

                if not resp.ok:
                    log("ERROR", f"Page {page_num_offset + 1} failed: {resp.error}")
                    break

                log("INFO", f"Page {page_num_offset + 1}: {resp.status_code} - {len(resp.text)} chars")

                try:
                    tree = lxml_html.fromstring(resp.content)
                except Exception as e:
                    log("ERROR", f"Failed to parse HTML: {e}")
                    break

                # Extract URLs
                urls = tree.xpath(LIST_XPATH)
                log("INFO", f"Page {page_num_offset + 1}: found {len(urls)} URLs")

                for u in urls:
                    if u and not u.startswith("http"):
                        u = urljoin(current_url, u)
                    if u and u.startswith("http"):
                        all_urls.append(u)

                time.sleep(INTERVAL)


    # Remove duplicates
    unique_urls = list(dict.fromkeys(all_urls))
    log("INFO", f"=== Crawl completed: {len(unique_urls)} unique URLs collected ===")

    # Save to database
    saved = save_urls_to_db(unique_urls)
    log("INFO", f"Saved {saved} new URLs to database")

    # Update task stats
    if saved > 0:
        update_task_stats(saved)
        log("INFO", f"Updated task stats: +{saved} crawled")

    return unique_urls


if __name__ == "__main__":
    asyncio.run(crawl())
