# -*- coding: utf-8 -*-
"""
Parse script for task 10
Mode: Parse-only - Read URLs from database, parse content, update database
Generated by Spider Manager V2.0
"""
import json
import asyncio
import datetime
import os
import sys
import pymysql
from lxml import html as lxml_html

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

ENGINE_NAME = "requests"
TIMEOUT = 30
HEADERS = {}

# Database config - from environment or defaults
DB_HOST = os.environ.get("SPIDER_DB_HOST", "192.168.1.191")
DB_PORT = int(os.environ.get("SPIDER_DB_PORT", "3308"))
DB_NAME = os.environ.get("SPIDER_DB_NAME", "spider_260519")
DB_TABLE = os.environ.get("SPIDER_DB_TABLE", "crawler_feachdata")
DB_USER = os.environ.get("SPIDER_DB_USER", "root")
DB_PASSWORD = os.environ.get("SPIDER_DB_PASSWORD", "")

# Task ID and Spider Name for data isolation
TASK_ID = 10
SPIDER_NAME = "spider_10_5b85b38b"

# XPath field mapping
FIELD_XPATHS = {
    "tag": """//div[@class="lft"]//span[contains(text(),'来源')]/text()""",
"title": '//meta[@name="ArticleTitle"]/@content',
"field1": '//meta[@name="ColumnType"]/@content',
"field2": '"重庆新闻"',
"content": '//*[@id="nrcon-left"]//text()',
"indexflag": '"0"',
"chubanriqi": '//meta[@name="PubDate"]/@content',

}


def log(level, msg):
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] [{level}] {msg}", flush=True)


def clean_text(text):
    if text is None:
        return ""
    if isinstance(text, list):
        text = " ".join(str(t) for t in text)
    return str(text).strip().replace("\n", " ").replace("\r", "").replace("\t", " ")


def get_unparsed_urls(limit=100):
    """Get URLs from database that haven't been parsed yet (filtered by spider_name)."""
    conn = pymysql.connect(
        host=DB_HOST, port=DB_PORT, user=DB_USER,
        password=DB_PASSWORD, database=DB_NAME,
        charset='utf8mb4', connect_timeout=10
    )
    cursor = conn.cursor()
    cursor.execute(
        f"SELECT id, url FROM `{DB_TABLE}` WHERE spider_name = %s AND (parseflag = 0 OR parseflag IS NULL) LIMIT %s",
        (SPIDER_NAME, limit)
    )
    rows = cursor.fetchall()
    cursor.close()
    conn.close()
    return rows


def update_record(record_id, data):
    """Update record with parsed data."""
    conn = pymysql.connect(
        host=DB_HOST, port=DB_PORT, user=DB_USER,
        password=DB_PASSWORD, database=DB_NAME,
        charset='utf8mb4', connect_timeout=10
    )
    cursor = conn.cursor()

    set_clauses = []
    values = []
    for key, value in data.items():
        if key != "url":
            set_clauses.append(f"`{key}` = %s")
            values.append(value)

    set_clauses.append("`parseflag` = 1")
    set_clauses.append("`lastmodifiedtime` = NOW()")

    values.append(record_id)
    sql = f"UPDATE `{DB_TABLE}` SET {', '.join(set_clauses)} WHERE id = %s"

    cursor.execute(sql, values)
    conn.commit()
    cursor.close()
    conn.close()


def update_task_stats(parsed_count):
    """Update task parse stats."""
    try:
        conn = pymysql.connect(
            host=DB_HOST, port=DB_PORT, user=DB_USER,
            password=DB_PASSWORD, database="spider",
            charset='utf8mb4', connect_timeout=10
        )
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE tasks SET total_parsed = total_parsed + %s WHERE id = %s",
            (parsed_count, TASK_ID)
        )
        conn.commit()
        cursor.close()
        conn.close()
    except Exception as e:
        log("WARNING", f"Failed to update task stats: {e}")


async def parse_url(url):
    """Parse a single URL and return extracted fields."""
    from app.engine.engine_factory import get_engine
    from app.engine import EngineConfig

    engine = get_engine(ENGINE_NAME)
    async with engine:
        ec = EngineConfig(url=url, headers=HEADERS, timeout=TIMEOUT)
        resp = await engine.fetch(ec)
        if not resp.ok:
            log("ERROR", f"Failed to fetch: {resp.error}")
            return None

        try:
            tree = lxml_html.fromstring(resp.content)
        except Exception as e:
            log("ERROR", f"Failed to parse HTML: {e}")
            return None

        result = {}

        for field_name, xpath in FIELD_XPATHS.items():
            try:
                # 判断是否为常量值（以双引号开头和结尾）
                if isinstance(xpath, str) and xpath.startswith('"') and xpath.endswith('"'):
                    # 常量值，直接赋值
                    result[field_name] = xpath[1:-1]
                    log("DEBUG", f"Field {field_name} = constant: {result[field_name]}")
                else:
                    # XPath表达式，从网页提取
                    values = tree.xpath(xpath)
                    if values:
                        result[field_name] = clean_text(values[0] if len(values) == 1 else values)
                    else:
                        result[field_name] = ""
            except Exception as e:
                log("WARNING", f"Field {field_name} parse error: {e}")
                result[field_name] = ""

        return result


async def run():
    """Main parse loop: read URLs from DB, parse, update DB."""
    log("INFO", "=== Starting parse job ===")

    rows = get_unparsed_urls(limit=1000)
    log("INFO", f"Found {len(rows)} URLs to parse")

    if not rows:
        log("INFO", "No URLs to parse, exiting")
        return

    total = len(rows)
    success = 0
    failed = 0

    for i, (record_id, url) in enumerate(rows, 1):
        log("INFO", f"[{i}/{total}] Parsing: {url}")

        try:
            result = await parse_url(url)
            if result:
                update_record(record_id, result)
                success += 1
                title = result.get('title', url)[:50]
                log("INFO", f"Parsed OK: {title}")
            else:
                failed += 1
                log("WARNING", f"Failed to parse")
        except Exception as e:
            failed += 1
            log("ERROR", f"Error: {e}")

        await asyncio.sleep(0.5)

    if success > 0:
        update_task_stats(success)

    log("INFO", f"=== Parse completed: {success} success, {failed} failed ===")


if __name__ == "__main__":
    asyncio.run(run())
