# -*- coding: utf-8 -*-
"""
Crawl script for task 12
Mode: Crawl-only - Collect URLs and save to database
Generated by Spider Manager V2.0
"""
import json
import time
import asyncio
import datetime
import os
import sys
import pymysql
from lxml import html as lxml_html
from urllib.parse import urljoin

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# === Configuration ===
START_URL = "https://www.flir.com/news-center/"
ENGINE_NAME = "my_play"
MAX_PAGES = 3
TIMEOUT = 30
INTERVAL = 1
HEADERS = {}

LIST_XPATH = '//div[@class="teaser-block__body"]/a/@href'

# Database config - from environment or defaults
DB_HOST = os.environ.get("SPIDER_DB_HOST", "192.168.1.191")
DB_PORT = int(os.environ.get("SPIDER_DB_PORT", "3308"))
DB_NAME = os.environ.get("SPIDER_DB_NAME", "spider_260519")
DB_TABLE = os.environ.get("SPIDER_DB_TABLE", "crawler_feachdata")
DB_USER = os.environ.get("SPIDER_DB_USER", "root")
DB_PASSWORD = os.environ.get("SPIDER_DB_PASSWORD", "")

# Task ID and Spider Name for data isolation
TASK_ID = 12
SPIDER_NAME = "spider_12_d5fa4b25"


def log(level, msg):
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] [{level}] {msg}", flush=True)


def update_task_crawled(count):
    """实时更新任务采集量"""
    try:
        conn = pymysql.connect(
            host=DB_HOST, port=DB_PORT, user=DB_USER,
            password=DB_PASSWORD, database="spider",
            charset='utf8mb4', connect_timeout=10
        )
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE tasks SET total_crawled = total_crawled + %s WHERE id = %s",
            (count, TASK_ID)
        )
        conn.commit()
        cursor.close()
        conn.close()
    except Exception as e:
        log("WARNING", f"Failed to update crawled count: {e}")


def save_url_to_db(url):
    """保存单个URL到数据库并实时更新采集量"""
    try:
        conn = pymysql.connect(
            host=DB_HOST, port=DB_PORT, user=DB_USER, 
            password=DB_PASSWORD, database=DB_NAME,
            charset='utf8mb4', connect_timeout=10
        )
        cursor = conn.cursor()

        # Check if URL already exists for this spider
        cursor.execute(f"SELECT id FROM `{DB_TABLE}` WHERE url = %s AND spider_name = %s", (url, SPIDER_NAME))
        if cursor.fetchone():
            cursor.close()
            conn.close()
            return False

        cursor.execute(
            f"INSERT INTO `{DB_TABLE}` (url, spider_name, parseflag) VALUES (%s, %s, 0)",
            (url, SPIDER_NAME)
        )
        conn.commit()
        cursor.close()
        conn.close()

        # 实时更新采集量
        update_task_crawled(1)
        return True
    except Exception as e:
        log("WARNING", f"Failed to insert URL: {e}")
        return False


async def crawl():
    import importlib.util

    # 加载引擎（支持内置和自定义引擎）
    def load_engine(engine_name):
        from app.engine.engine_factory import get_engine

        script_dir = os.path.dirname(os.path.abspath(__file__))
        scripts_dir = os.path.dirname(script_dir)
        data_dir = os.path.dirname(scripts_dir)
        custom_engines_dir = os.path.join(data_dir, "custom_engines")
        custom_engine_path = os.path.join(custom_engines_dir, f"{engine_name}.py")

        if os.path.exists(custom_engine_path):
            spec = importlib.util.spec_from_file_location(f"custom_engine_{engine_name}", custom_engine_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            class CustomEngineWrapper:
                def __init__(self, module):
                    self.module = module

                async def fetch(self, config):
                    import asyncio
                    result = self.module.fetch(
                        url=config.url,
                        headers=config.headers,
                        timeout=config.timeout,
                        proxy=getattr(config, 'proxy', None),
                    )

                    if asyncio.iscoroutine(result):
                        result = await result

                    from app.engine import RawResponse
                    return RawResponse(
                        url=config.url,
                        status_code=200,
                        headers=dict(),
                        text=result,
                        content=result.encode('utf-8') if isinstance(result, str) else result,
                        encoding='utf-8',
                    )

                async def __aenter__(self):
                    return self

                async def __aexit__(self, *args):
                    pass

            return CustomEngineWrapper(module)
        else:
            return get_engine(engine_name)

    from app.engine import EngineConfig

    engine = load_engine(ENGINE_NAME)
    all_urls = []
    saved_count = 0

    async with engine:

            # XPath翻页模式
            current_url = START_URL
            for page in range(1, MAX_PAGES + 1):
                log("INFO", f"Fetching page {page}: {current_url}")
                ec = EngineConfig(url=current_url, headers=HEADERS, timeout=TIMEOUT)
                resp = await engine.fetch(ec)

                if not resp.ok:
                    log("ERROR", f"Page {page} failed: {resp.error}")
                    break

                log("INFO", f"Page {page}: {resp.status_code} - {len(resp.text)} chars")

                try:
                    tree = lxml_html.fromstring(resp.content)
                except Exception as e:
                    log("ERROR", f"Failed to parse HTML: {e}")
                    break

                # Extract URLs
                urls = tree.xpath(LIST_XPATH)
                log("INFO", f"Page {page}: found {len(urls)} URLs")

                for u in urls:
                    if u and not u.startswith("http"):
                        u = urljoin(current_url, u)
                    if u and u.startswith("http"):
                        all_urls.append(u)

                # Find next page
                NEXT_XPATH = '//button[@id="alb-12835-page-next"]/@href'
                if NEXT_XPATH:
                    next_links = tree.xpath(NEXT_XPATH)
                    if next_links:
                        next_url = next_links[0] if isinstance(next_links[0], str) else ""
                        if next_url:
                            if not next_url.startswith("http"):
                                next_url = urljoin(current_url, next_url)
                            current_url = next_url
                            log("INFO", f"Next page: {current_url}")
                        else:
                            log("INFO", "Next link empty, stopping")
                            break
                    else:
                        log("INFO", "No next page found, stopping")
                        break
                else:
                    log("INFO", "No pagination config, stopping")
                    break

                time.sleep(INTERVAL)


    # Remove duplicates
    unique_urls = list(dict.fromkeys(all_urls))
    log("INFO", f"=== Crawl completed: {len(unique_urls)} unique URLs collected ===")

    # Save to database one by one with real-time stats update
    for u in unique_urls:
        if save_url_to_db(u):
            saved_count += 1
            log("INFO", f"Saved URL {saved_count}: {u[:80]}...")

    log("INFO", f"=== Total saved: {saved_count} new URLs ===")

    return unique_urls


if __name__ == "__main__":
    asyncio.run(crawl())
